# @package _global_

xpname: glo12-sla-8th-unet

datamodule:
  input_da:
    _target_: contrib.glorys12.load_glorys12_data_on_fly_inp
    tgt_path: /SCRATCH/h21georg/glorys12_2010_2019_daily_sla_8th_float32.nc
    inp_path: /SCRATCH/h21georg/glorys12_2010_2019_daily_sla_8th_input.nc
  xrds_kw:
    train:
      # path_dims: {time: 15, lat: 1360, lon: 2880}
      # strides: {time: 1, lat: 1344, lon: 2864}
      path_dims: {time: 15, lat: 96, lon: 96}
      strides: {time: 1, lat: 80, lon: 80}
      noise: .03
    val:
      # path_dims: {time: 15, lat: 1360, lon: 2880}
      # strides: {time: 1, lat: 1344, lon: 2864}
      path_dims: {time: 15, lat: 664, lon: 1456}
      strides: {time: 1, lat: 632, lon: 1424}
      noise: .03
  norm_stats:  # norm values from tgt
    train:
    - -0.00178148283157497640
    - 0.0329529345035553
    val:
    - 0.014355200342833996
    - 0.055344343185424805

defaults:
  - glo12-sla-unet
  - _self_
