# @package _global_
xpname: glo12-sla-4th-fdv++-stride

#ckpt: null
ckpt: null # 'outputs/2025-08-26/glo12-sla-4th-fdv++-13-23-14/glo12-sla-4th-fdv/checkpoints/best.ckpt'

trainer:
  check_val_every_n_epoch: 3
  max_epochs: 1000
  limit_train_batches: 50 #250

datamodule:
  xrds_kw:
    train:
      patch_dims: {time: 15, lat: 256, lon: 256}
      strides: {time: 1, lat: 196, lon: 154}
      domain_limits: ${domain.train}
      noise: .03
    val:
      patch_dims: {time: 15, lat: 512, lon: 512}
      strides: {time: 1, lat: 136, lon: 488}
      domain_limits: ${domain.train}
      noise: .03
  #dl_kw: {batch_size: 8, num_workers: 4}
  dl_kw: {batch_size: 8, num_workers: 4}

model:
  _target_: contrib.4dvarnet_latent.models.Lit4dVarNetIgnoreNaN
  w_mse: 50.
  w_grad_mse: 1000.
  w_prior: 1.
  w_mse_lr: 0.
  w_grad_mse_lr: 0
  opt_fn:
    _target_: contrib.unet_multi_cascade.cosanneal_lr_adam
    _partial_: true
    lr: 1e-4
    T_max: ${trainer.max_epochs}
  solver:
    _target_: contrib.unet_multi_cascade.GradSolver_cascade
    n_step: 10 #10
    lr_grad: 0. #1e3
    std_latent_init: 0.1    
    # lr_grad: 0.2
    prior_cost:
      _target_: contrib.4dvarnet_latent.models.BilinAEPriorCostTwoScale # 
      #_target_: ocean4dvarnet.models.BilinAEPriorCost
      dim_in: 15 #${datamodule.xrds_kw.train.patch_dims.time}+${model.solver.latent_decoder.dim_latent}
      dim_hidden: 128
      bilin_quad: false
      # bilin_quad: true
      downsamp: 4 #null # 4
      bias: false
    prior_cost_low:
      _target_: contrib.4dvarnet_latent.models.BilinAEPriorCostTwoScale # 
      #_target_: ocean4dvarnet.models.BilinAEPriorCost
      dim_in: 15 #${datamodule.xrds_kw.train.patch_dims.time}+${model.solver.latent_decoder.dim_latent}
      dim_hidden: 64
      bilin_quad: false
      # bilin_quad: true
      downsamp: 4 #null # 4
      bias: false
    obs_cost:
      _target_: contrib.unet_multi_cascade.BaseObsCost
    grad_mod:
      _target_: contrib.unet_multi_cascade.UnetGradModel
      dim_in: ${datamodule.xrds_kw.train.patch_dims.time}
      embed_dim: 256
      dim_hidden: 32
      num_levels: 4   
    grad_mod_low:
      _target_: contrib.unet_multi_cascade.UnetGradModel
      dim_in: ${datamodule.xrds_kw.train.patch_dims.time}
      embed_dim: 256
      dim_hidden: 16
      num_levels: 4 
defaults:
  - glo12-sla-4th-unet
  - _self_
