# @package _global_
xpname: glo12-sla-4th-latent-small-batches

trainer:
  check_val_every_n_epoch: 3
  max_epochs: 350
  limit_train_batches: 50 #250

datamodule:
  input_da:
    #_target_: contrib.glorys12.load_glorys12_data
    _target_: contrib.glorys12.load_glorys12_data_on_fly_inp
    tgt_path: /SCRATCH/rfablet/Dataset/glorys12_2010_2019_daily_sla_4th.nc #/Odyssey/public/glorys/reanalysis/glorys12_2010_2019_daily_sla_4th.nc #glorys4_2010_2019_sla.nc
    inp_path: /SCRATCH/rfablet/Dataset/mask_6nadirs_4th.nc     
    inp_var: inp
    #inp_path: /SCRATCH/rfablet/Dataset/glorys12_2010_2019_daily_sla_4th_input.nc
    #tgt_path: /SCRATCH/rfablet/Dataset/glorys12_2010_2019_daily_sla_4th_2018-2019.nc
    #inp_path: /SCRATCH/rfablet/Dataset/glorys12_2010_2019_daily_sla_4th_input_2018-2019.nc 
    #inp_path: /SCRATCH/rfablet/Dataset/glorys12_2010_2019_daily_sla_4th_input.nc 
    #tgt_path: /SCRATCH/rfablet/Dataset/glorys12_2010_2019_daily_sla_4th.nc
    #tgt_path: /Odyssey/public/glorys/reanalysis/glorys12_2010_2019_daily_sla_4th.nc
    #inp_path: /Odyssey/public/glorys/reanalysis/glorys12_2010_2019_daily_sla_4th_input.nc
    #inp_var: sla
  domains:
    train:
      time: {_target_: builtins.slice, _args_: ['2010-01-01', '2018-12-31']}
    val:
      time: {_target_: builtins.slice, _args_: ['2019-01-01', '2019-12-31']}
  xrds_kw:
    train:
      patch_dims: {time: 15, lat: 256, lon: 256}
      strides: {time: 1, lat: 240, lon: 240}
      domain_limits: ${domain.train}
      noise: .03
    val:
      patch_dims: {time: 15, lat: 512, lon: 512}
      strides: {time: 1, lat: 500, lon: 500}
      domain_limits: ${domain.train}
      noise: .03
  #dl_kw: {batch_size: 8, num_workers: 4}
  dl_kw: {batch_size: 16, num_workers: 4}

defaults:
  - glo12-sla-8th-4dvarnet-latent
  - _self_