# @package _global_
xpname: glo12-sla-4th-unet-2010-2017-2000epochs

ckpt: null 

trainer:
  check_val_every_n_epoch: 3
  max_epochs: 2000
  limit_train_batches: 250

datamodule:  
  input_da:
#    _target_: contrib.glorys12.load_glorys12_data
    _target_: contrib.glorys12.load_glorys12_data_on_fly_inp
    #_target_: contrib.glorys12.load_glorys12_data_on_fly_inp #contrib.glorys12.load_glorys12_data
    #inp_path: /SCRATCH/rfablet/Dataset/glorys12_2010_2019_daily_sla_4th_input.nc
#    inp_path: /Odyssey/public/glorys/reanalysis/glorys12_2010_2019_daily_sla_4th_input.nc 
#    tgt_path: /Odyssey/public/glorys/reanalysis/glorys12_2010_2019_daily_sla_4th.nc
    #inp_path: /SCRATCH/rfablet/Dataset/glorys12_2010_2019_daily_sla_4th_input_2018-2019.nc     
    tgt_path: /SCRATCH/rfablet/Dataset/glorys12_2010_2019_daily_sla_4th_float32.nc 
    inp_path: /SCRATCH/rfablet/Dataset/mask_6nadirs_4th.nc     
    inp_var: inp
  domains:
    train:
      time: {_target_: builtins.slice, _args_: ['2010-01-01', '2017-12-31']}
    val:
      time: {_target_: builtins.slice, _args_: ['2018-01-01', '2018-12-31']}
    test: null
  xrds_kw:
    train:
      patch_dims: {time: 15, lat: 256, lon: 256}
      strides: {time: 1, lat: 100, lon: 100}
      domain_limits: ${domain.train}
      noise: .1
      noise_type: gaussian+uniform
    val:
      patch_dims: {time: 15, lat: 512, lon: 512}
      strides: {time: 1, lat: 500, lon: 500}
      domain_limits: ${domain.train}
      noise: .03
      noise_type: uniform
  dl_kw: {batch_size: 32, num_workers: 4}
model:
  _target_: contrib.4dvarnet_latent.models.LitUnetFromLit4dVarNetIgnoreNaN
  w_mse: 50.
  w_grad_mse: 1000.
  opt_fn:
    _target_: contrib.4dvarnet_latent.models.cosanneal_lr_adam_base
    _partial_: true
    lr: 1e-4
    T_max: ${trainer.max_epochs}
  solver:
    _target_: contrib.4dvarnet_latent.unet.UNetModel #ocean4dvarnet.models.GradSolver
    in_channels: 15 #${datamodule.xrds_kw.train.patch_dims.time}
    model_channels: 128
    out_channels: 15
    num_res_blocks: 4
    attention_resolutions: [2]
    dropout: 0.3
    channel_mult: [2, 2, 2]
    conv_resample: false
    dims: 2
    use_checkpoint: false
    num_heads: 1
    num_head_channels: -1
    num_heads_upsample: -1
    use_scale_shift_norm: true
    resblock_updown: false
    use_new_attention_order: true
    with_fourier_features: false
defaults:
  - glo12-sla-base
  - _self_
