# @package _global_
xpname: glo12-sla-8th-fdv-latent
ckpt: null

trainer:
  check_val_every_n_epoch: 3
  max_epochs: 350
  limit_train_batches: 250

datamodule:
  _target_: contrib.glorys12.DistinctNormDataModule #contrib.glorys12.DistinctNormDataModuleWithLonLat # # #
  input_da:
    _target_: contrib.glorys12.load_glorys12_data_on_fly_inp
    tgt_path: /SCRATCH/rfablet/Dataset/glorys12_2010_2019_daily_sla_8th_float32.nc 
    inp_path: /SCRATCH/rfablet/Dataset/mask_6nadirs_8th.nc     # from /Odyssey/public/data_challenge_ssh_ose/data/alongtrack/
    inp_var: inp
  xrds_kw:
    train:
      patch_dims: {time:  15, lat: 512, lon: 512}
      strides: {time: 1, lat: 200, lon: 200}
      domain_limits: ${domain.train}
      noise: .03
      noise_type: uniform
    val:
      patch_dims: {time: 15, lat: 800, lon: 800}
      strides: {time: 1, lat: 700, lon: 700}
      noise: .03
      noise_type: uniform
  dl_kw: {batch_size: 16, num_workers: 4}


model:
  _target_: contrib.4dvarnet_latent.models.Lit4dVarNetIgnoreNaNLatent
  w_mse: 50.
  w_grad_mse: 1000.
  w_mse_lr: 50.
  w_grad_mse_lr: 1000.
  w_prior: 1.
  w_latent_ae: 1.
  solver:
    _target_: contrib.4dvarnet_latent.models.GradSolverWithLatent #ocean4dvarnet.models.GradSolver
    n_step: 15
    lr_grad: 1e3
    std_latent_init: 0.1    
    # lr_grad: 0.2
    latent_decoder:
      _target_: contrib.4dvarnet_latent.models.LatentDecoderMR
      dim_state: ${datamodule.xrds_kw.train.patch_dims.time}
      dim_latent: 8
      channel_dims: 16
      scale_factor: 4
      interp_mode: 'bilinear'
    latent_encoder:
      _target_: contrib.4dvarnet_latent.models.LatentEncoderMR
      dim_state: ${datamodule.xrds_kw.train.patch_dims.time}
      dim_latent: ${model.solver.latent_decoder.dim_latent} #8
      channel_dims: 16
      scale_factor: ${model.solver.latent_decoder.scale_factor}
    prior_cost:
      _target_: ocean4dvarnet.models.BilinAEPriorCost
      dim_in: 23 #${datamodule.xrds_kw.train.patch_dims.time}+${model.solver.latent_decoder.dim_latent}
      dim_hidden: 64
      bilin_quad: false
      # bilin_quad: true
      downsamp:  null
    obs_cost:
      _target_: ocean4dvarnet.models.BaseObsCost
    grad_mod:
      _target_: ocean4dvarnet.models.ConvLstmGradModel #contrib.4dvarnet_latent.models.ConvLstmGradModel #
      dim_in: ${model.solver.prior_cost.dim_in} #${datamodule.xrds_kw.train.patch_dims.time}
      dim_hidden: 96

defaults:
  - glo12-sla-base
  - _self_