# @package _global_
xpname: glo12-sla-4th-unet2-noise2+

ckpt: null #./outputs/2025-08-12/glo12-sla-4th-unet-09-01-30/glo12-sla-4th-unet/checkpoints/last.ckpt
#ckpt: null #./outputs/2025-08-12/glo12-sla-4th-unet-noise2-19-24-46/glo12-sla-4th-unet/checkpoints//last.ckpt
#ckpt: outputs/2025-08-13/glo12-sla-4th-unet-noise2+-07-34-32/glo12-sla-4th-unet/checkpoints/last.ckpt

trainer:
  check_val_every_n_epoch: 3
  max_epochs: 350
  limit_train_batches: 250

datamodule:  
  input_da:
#    _target_: contrib.glorys12.load_glorys12_data
    _target_: contrib.glorys12.load_glorys12_data_on_fly_inp
    #_target_: contrib.glorys12.load_glorys12_data_on_fly_inp #contrib.glorys12.load_glorys12_data
    #tgt_path: /SCRATCH/rfablet/Dataset/glorys12_2010_2019_daily_sla_4th.nc #/Odyssey/public/glorys/reanalysis/glorys12_2010_2019_daily_sla_4th.nc #glorys4_2010_2019_sla.nc
    #inp_path: /SCRATCH/rfablet/Dataset/glorys12_2010_2019_daily_sla_4th_input.nc
#    inp_path: /Odyssey/public/glorys/reanalysis/glorys12_2010_2019_daily_sla_4th_input.nc 
#    tgt_path: /Odyssey/public/glorys/reanalysis/glorys12_2010_2019_daily_sla_4th.nc
    #inp_path: /SCRATCH/rfablet/Dataset/glorys12_2010_2019_daily_sla_4th_input_2018-2019.nc 
    inp_path: /SCRATCH/rfablet/Dataset/mask_6nadirs_4th.nc     
    inp_var: inp
  domains:
    train:
      time: {_target_: builtins.slice, _args_: ['2010-01-01', '2018-12-31']}
    val:
      time: {_target_: builtins.slice, _args_: ['2019-01-01', '2019-12-31']}
    test: null
  xrds_kw:
    train:
      patch_dims: {time: 15, lat: 128, lon: 256}
      strides: {time: 1, lat: 100, lon: 100}
      domain_limits: ${domain.train}
      noise: .1
      noise_type: gaussian+uniform
    val:
      patch_dims: {time: 15, lat: 512, lon: 512}
      strides: {time: 1, lat: 500, lon: 500}
      domain_limits: ${domain.train}
      noise: .03
      noise_type: gaussian+uniform
  dl_kw: {batch_size: 32, num_workers: 4}
model:
  _target_: contrib.4dvarnet_latent.models.LitUnetFromLit4dVarNetIgnoreNaN
  w_mse: 50.
  w_grad_mse: 1000.
  opt_fn:
    _target_: contrib.4dvarnet_latent.models.cosanneal_lr_adam_base
    _partial_: true
    lr: 1e-4
    T_max: ${trainer.max_epochs}
  solver:
    _target_: contrib.4dvarnet_latent.models.UnetSolver2 #ocean4dvarnet.models.GradSolver
    dim_in: 15 #${datamodule.xrds_kw.train.patch_dims.time}
    channel_dims: [64, 64, 64, 128, 128, 128, 256, 256, 256, 512]

defaults:
  - glo12-sla-base
  - _self_
