# @package _global_
xpname: glo12-sla-4th-fdv++-ft-noiseSpRv2-acc2

#ckpt: null
#ckpt: 'outputs/2025-08-26/glo12-sla-4th-fdv++-13-23-14/glo12-sla-4th-fdv/checkpoints/best.ckpt'
ckpt: outputs/2025-09-19/glo12-sla-4th-fdv++-ft-noiseSpRv2-09-07-17/glo12-sla-4th-fdv++/checkpoints/last.ckpt

#ckpt: ./outputs/2025-08-30/glo12-sla-4th-fdv++-noise+-10-13-47/glo12-sla-4th-fdv/checkpoints/best.ckpt
#config_path: ./outputs/2025-08-30/glo12-sla-4th-fdv++-noise+-10-13-47/.hydra/config.yaml


trainer:
  check_val_every_n_epoch: 3
  max_epochs: 2000
  limit_train_batches: 100 #250
  accumulate_grad_batches: 2 #8

datamodule:
  xrds_kw:
    train:
      patch_dims: {time: 15, lat: 256, lon: 256}
      strides: {time: 1, lat: 196, lon: 154}
      domain_limits: ${domain.train}
      noise_type: gaussian+uniform # spatial-perturb # 
      noise: .03
    val:
      patch_dims: {time: 15, lat: 512, lon: 512}
      strides: {time: 1, lat: 136, lon: 488}
      domain_limits: ${domain.train}
      noise: .03
      noise_type: null #uniform-constant #uniform-constant spatial-perturb
  #dl_kw: {batch_size: 8, num_workers: 4}
  dl_kw: {batch_size: 4, num_workers: 4}

model:
  _target_:  contrib.4dvarnet_latent.models.Lit4dVarNetIgnoreNaN
  w_mse: 50.
  w_grad_mse: 1000.
  w_prior: 1.
  w_mse_lr: 0.
  w_grad_mse_lr: 0
  solver:
    _target_: contrib.4dvarnet_latent.models.GradSolverZeroInit #ocean4dvarnet.models.GradSolver
    n_step: 15 #10
    lr_grad: 0. #1e3
    std_latent_init: 0.1    
    osse_with_interp_error: true
    # lr_grad: 0.2
    prior_cost:
      _target_: contrib.4dvarnet_latent.models.BilinAEPriorCostTwoScale # 
      dim_in: 15 #${datamodule.xrds_kw.train.patch_dims.time}+${model.solver.latent_decoder.dim_latent}
      dim_hidden: 128 #128 #64
      bilin_quad: false
      # bilin_quad: true
      downsamp: 4 #4 #null # 4
      bias: false
    obs_cost:
      _target_: ocean4dvarnet.models.BaseObsCost
    grad_mod:
      _target_: contrib.4dvarnet_latent.models.ConvLstmGradModelUnet #contrib.4dvarnet_latent.models.ConvLstmGradModel #
      dim_in: ${model.solver.prior_cost.dim_in} #${datamodule.xrds_kw.train.patch_dims.time}
      dim_hidden: 64 #128 #96
      bias: false
      unet:
        _target_: contrib.4dvarnet_latent.models.UnetSolverBilin
        dim_in: ${model.solver.grad_mod.dim_hidden}
        dim_out: ${model.solver.prior_cost.dim_in}
        channel_dims: [64, 64, 64, 128, 128, 128, 128, 128, 128, 128]
        dropout: 0.1
        bias: false
      dropout: 0.1
entrypoints:
  - _target_: pytorch_lightning.seed_everything
    seed: 333 #111 #
  - _target_: contrib.glorys12.train
    trainer: ${trainer}
    lit_mod: ${model}
    dm: ${datamodule}
    ckpt: ${ckpt}
#  - _target_: contrib.glorys12.train_from_pretrained_model
#    trainer: ${trainer}
#    lit_mod: ${model}
#    dm: ${datamodule}
#    config_path: ${config_path}
#    ckpt_path: ${ckpt}
defaults:
  - glo12-sla-4th-unet
  - _self_