# @package _global_

trainer:
  check_val_every_n_epoch: 5

model:
   solver:
    _target_: contrib.4dvarnet_latent.GradSolverWithLatent #ocean4dvarnet.models.GradSolver
    n_step: 15
    lr_grad: 1e3

    # lr_grad: 0.2
    latent_decoder:
      _target_: contrib.4dvarnet_latent.LatentDecoderMR
      dim_state: ${datamodule.xrds_kw.train.patch_dims.time}
      dim_latent: 8
      channel_dims: 16
      scale_factor: 4
      interp_mode: 'linear'
    prior_cost:
      _target_: ocean4dvarnet.models.BilinAEPriorCost
      dim_in: ${datamodule.xrds_kw.train.patch_dims.time}
      dim_hidden: 64
      bilin_quad: false
      # bilin_quad: true
      downsamp: 0
    obs_cost:
      _target_: ocean4dvarnet.models.BaseObsCost
    grad_mod:
      _target_: ocean4dvarnet.models.ConvLstmGradModel
      dim_in: ${datamodule.xrds_kw.train.patch_dims.time}
      dim_hidden: 96

defaults:
  - glo12-sla
  - _self_