domain:
  train:
    lat:
      _target_: builtins.slice
      _args_:
      - -80
      - 90
    lon:
      _target_: builtins.slice
      _args_:
      - -180
      - 180
  test:
    lat:
      _target_: builtins.slice
      _args_:
      - -79
      - 89
    lon:
      _target_: builtins.slice
      _args_:
      - -179
      - 179
ckpt: null
xpname: glo12-sla-unet-big
trainer:
  _target_: pytorch_lightning.Trainer
  inference_mode: false
  deterministic: true
  gradient_clip_val: 0.5
  accelerator: gpu
  devices: 1
  logger:
    _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
    save_dir: ${hydra:runtime.output_dir}
    name: ${hydra:runtime.choices.xp}
    version: ''
  max_epochs: 1000
  limit_train_batches: 100
  callbacks:
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: val_mse
    save_last: true
    save_top_k: 3
    filename: '{val_mse:.5f}-{epoch:03d}'
datamodule:
  _target_: contrib.glorys12.DistinctNormDataModule
  input_da:
    _target_: contrib.glorys12.load_glorys12_data
    tgt_path: /Odyssey/public/glorys/reanalysis/glorys4_2010_2019_sla.nc
    tgt_var: sla
    inp_path: /Odyssey/public/glorys/input/glorys4_2010_2019_input_sla.nc
    inp_var: sla
  domains:
    train:
      time:
        _target_: builtins.slice
        _args_:
        - '2010-01-01'
        - '2018-11-30'
    val:
      time:
        _target_: builtins.slice
        _args_:
        - '2019-01-01'
        - '2019-12-31'
    test: null
  xrds_kw:
    train:
      patch_dims:
        time: 15
        lat: 1360
        lon: 2880
      strides:
        time: 1
        lat: 1344
        lon: 2864
      domain_limits: ${domain.train}
    val:
      patch_dims:
        time: 15
        lat: 1360
        lon: 2880
      strides:
        time: 1
        lat: 1344
        lon: 2864
      domain_limits: ${domain.train}
  dl_kw:
    batch_size: 1
    num_workers: 2
  norm_stats:
    train:
    - -0.001930378327255099
    - 0.08604745118775728
    val:
    # - 0.01560162689028551
    # - 0.08583080433051968
    - -0.001930378327255099
    - 0.08604745118775728
model:
  _target_: contrib.unet.models.UnetBig
  solver:
    _target_: contrib.unet.models.UnetSolverBig
    _partial_: True
    n_channels: 15
    n_classes: 15
    bilinear: True
    block:
      _target_: contrib.unet.parts.StandardBlock
      _partial_: True
    add_input: False
  opt_fn:
    _target_: contrib.unet.utils.cosanneal_lr_adam
    _partial_: true
    lr: 1e-4 #lowered from 1e-3
    T_max: ${trainer.max_epochs}
  rec_weight:
    _target_: ocean4dvarnet.utils.get_triang_time_wei
    patch_dims: ${datamodule.xrds_kw.train.patch_dims}
    crop: {time: 0, lat: 4, lon: 4}
  pre_metric_fn:
        _target_: xarray.Dataset.sel
        _partial_: True
        time: {_target_: builtins.slice, _args_: ["2019-11-25", "2019-12-31"]}
        lat: ${domain.test.lat}
        ltorch.nan_to_num(x)on: ${domain.test.lon}
  norm_stats: ${datamodule.norm_stats}
entrypoints:
- _target_: pytorch_lightning.seed_everything
  seed: 333
- _target_: contrib.glorys12.train
  trainer: ${trainer}
  lit_mod: ${model}
  dm: ${datamodule}
  ckpt: ${ckpt}
