# @package _global_
#xpname: glo12-sla-4th-unet15M-unrolling-5iter-randinit-subgrad+state-ossev2-noiseg+u03
#xpname: glo12-sla-4th-unnrolling-test-ossev1-noiseg+u03
#xpname: glo12-sla-4th-unet15M-fm-gradonly-ossev1-noiseg+u03
#xpname: glo12-sla-4th-unet15M-fm+e2e-subgrad+state-5iter-ossev2-noiseg+u03
#xpname: glo12-sla-4th-unet15M-unrolling-5iter-v2-subgrad+state-ossev2-noiseg+u03
#xpname: glo12-sla-4th-unet15M-unrolling-aeunet-5iter-subgrad+state-ossev2-noiseg+u03
#xpname: glo12-sla-4th-unet15M-unrolling-aeunet-mergedtimesteps-5iter-subgrad+state-ossev2-noiseg+u03
#xpname: glo12-sla-4th-unet15M-unrolling-aeunet_64_2_96_3-randinit-5iter-subgrad+state-ossev2-noiseg+u03
xpname: glo12-sla-4th-unet15M-unrolling-aeunet_64_2_96_3-randinit-5iter-grad+state-ossev2-noiseg+u03
#xpname: glo12-sla-4th-unet15M-unrolling-5iter-v2bis-obs+state-ossev2-noiseg+u03

ckpt: null
#ckpt: ./outputs/2025-12-04/glo12-sla-4th-unet15M-unrolling-aeunet-randinit-5iter-subgrad+state-ossev2-noiseg+u03-23-56-02/glo12-sla-4th-unrolling-ossev1/checkpoints/last.ckpt
#config_path: ./outputs/2025-12-04/glo12-sla-4th-unet15M-unrolling-aeunet-randinit-5iter-subgrad+state-ossev2-noiseg+u03-23-56-02/.hydra/config.yaml

trainer:
  check_val_every_n_epoch: 3
  max_epochs: 2000
  limit_train_batches: 100 #250
  accumulate_grad_batches: 1 #8

  callbacks:
    - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      monitor: val_loss
      save_last: true
      save_top_k: 3
      filename: '{val_loss:.5f}-{epoch:03d}'


datamodule:  
  _target_: contrib.glorys12.DistinctNormDataModulewInputTracks
  input_da:
    _target_: contrib.glorys12.load_glorys12_data_on_fly_inp
    tgt_path: /Odyssey/public/glorys/reanalysis/glorys12_2010_2019_daily_sla_4th_gridded_from_alongtrack.nc #glorys12_2010_2019_daily_sla_4th_target_gridded_alongtrack.nc #/Odyssey/public/glorys/reanalysis/glorys12_2010_2019_daily_sla_4th_target_gridded_alongtrack.nc
    inp_path: /Odyssey/public/glorys/reanalysis/glorys12_2010_2019_daily_sla_4th_gridded_from_alongtrack.nc #glorys12_2010_2019_daily_sla_4th_input_gridded_alongtrack.nc #/Odyssey/public/glorys/reanalysis/glorys12_2010_2019_daily_sla_4th_input_gridded_alongtrack.nc
    inp_var: obs #sla
    tgt_var: tgt #sla
  domains:
    train:
      time: {_target_: builtins.slice, _args_: ['2010-01-01', '2017-12-31']}
    val:
      time: {_target_: builtins.slice, _args_: ['2018-01-01', '2018-12-31']}
    test: null
  xrds_kw:
    train:
      patch_dims: {time: 15, lat: 256, lon: 256}
      strides: {time: 1, lat: 196, lon: 154}
      domain_limits: ${domain.train}
      noise: 0.03
      noise_type: gaussian+uniform # spatial-perturb # 
    val:
      patch_dims: {time: 15, lat: 512, lon: 512}
      strides: {time: 1, lat: 136, lon: 488}
      domain_limits: ${domain.train}
      noise: .03
      noise_type: gaussian+uniform #uniform-constant #null # #uniform-constant spatial-perturb
  dl_kw: {batch_size: 4, num_workers: 4}
  #dl_kw: {batch_size: 4, num_workers: 4}

model:
  _target_:  contrib.4dvarnet_latent.models.Lit4dVarNetIgnoreNaN #Lit4dVarNetIgnoreNaN_MergeTimeSteps # #_FM_E2E
  w_mse: 50.
  w_grad_mse: 1000.
  w_prior: 1. #1.
  w_mse_lr: 0.
  w_grad_mse_lr: 0
  osse_with_interp_error: false #true
  #use_fm_learning: true
  solver:
    _target_: contrib.4dvarnet_latent.models.GradSolver_withStep #GradSolver_FM #GradSolver_withStep # # # # # ##GradSolver_FM # #ocean4dvarnet.models.GradSolver
    n_step: 5 #2 #5 #10
    lr_grad: 0. #1e3
    std_init: 0.1
    input_grad_update: 'grad+state' #'obs+state' ##'grad-only' #'grad+state' #'obs-only'  # 'grad+previous'  #'gobs+sgprior' #'grad+state'  #'grad-only' #'grad+state'  #'grad+state' #    
    # lr_grad: 0.2
    prior_cost:
      _target_: contrib.4dvarnet_latent.models.GenericAEPriorCost
      model_ae:
        _target_: contrib.4dvarnet_latent.unet.UNetModel
        dims: 2
        in_channels: 15 #15 #${datamodule.xrds_kw.train.patch_dims.time}
        out_channels: 15 #${datamodule.xrds_kw.train.patch_dims.time}
        model_channels: 64 #64 #32
        num_res_blocks: 2
        channel_mult: [1,2,4]
        attention_resolutions: []
        use_checkpoint: true
        dropout: 0.1
        bias: false #true #
    obs_cost:
      _target_: ocean4dvarnet.models.BaseObsCost
    grad_mod:
      _target_: contrib.4dvarnet_latent.models.GradModelWithCondition
      use_grad_norm: false
      grad_model: 
        _target_: contrib.4dvarnet_latent.unet.UNetModel2
        dims: 2
        in_channels: 30 #45 #${datamodule.xrds_kw.train.patch_dims.time}
        out_channels: 15 #15 #${datamodule.xrds_kw.train.patch_dims.time}
        model_channels: 96 #96 #64 #32
        num_res_blocks: 3 #3 #2
        channel_mult: [1,2,4]
        attention_resolutions: []
        use_checkpoint: true
        dropout: 0.1
        bias: false #true #
        interp_mode: 'bilinear' #'nearest' # 
      # grad_model: 
      #  _target_: contrib.4dvarnet_latent.unet_3d_film.UNet3D_Transformer
      #  in_channels: 3
      #  channels: [64,64,128,128]        # depth over width
      #  embed_dim: 256
      #  dropout: 0.1                       # set to 0.05–0.20 per your dataset size
      #  attn_heads: 1
      #  text_dim: 1                         # kept for signature compatibility
      #  nAttr: 40  
  #rec_weight:
  #  _target_: ocean4dvarnet.utils.get_triang_time_wei
  #  patch_dims: {time: 7, lat: 256, lon: 256}
  #  crop: {time: 0, lat: 4, lon: 4}
  #val_rec_weight:
  #  _target_: ocean4dvarnet.utils.get_triang_time_wei
  #  patch_dims: {time: 7, lat: 512, lon: 512}
  #  crop: {time: 0, lat: 4, lon: 4}
entrypoints:
  - _target_: pytorch_lightning.seed_everything
    seed: 333 #111 #
  - _target_: contrib.glorys12.train
    trainer: ${trainer}
    lit_mod: ${model}
    dm: ${datamodule}
    ckpt: ${ckpt}
#  - _target_: contrib.glorys12.train_from_pretrained_model
#    trainer: ${trainer}
#    lit_mod: ${model}
#    dm: ${datamodule}
#    config_path: ${config_path}
#    ckpt_path: ${ckpt}
defaults:
  - glo12-sla-4th-unet
  - _self_