method:
  # -------------------------------------------------------------------
  # SLA
  # -------------------------------------------------------------------
  geo_uv: false
  normalization_type: none #norm_stats_from_patch
  obs_filtering: false #true
  interp_on_mdt_grid: false #true
  ensemble_mean_from_noise: true #true
  std_noise_input: 0.25
#  name: unet-4th-glo12-sla
#  checkpoint: ../outputs/2025-08-12/glo12-sla-4th-unet-12-52-27/glo12-sla-4th-unet/checkpoints/best.ckpt
#  config: ../outputs/2025-08-12/glo12-sla-4th-unet-12-52-27/.hydra/config.yaml

#  name: unet-4th-glo12-sla-with-init
#  checkpoint: ../outpxuts/2025-08-12/glo12-sla-4th-unet-with-init-12-52-56/glo12-sla-4th-unet-with-init/checkpoints/best.ckpt
#  config: ../outputs/2025-08-12/glo12-sla-4th-unet-with-init-12-52-56/.hydra/config.yaml

#  name: unet-noise2-4th-glo12-sla-best2
#  checkpoint: ../outputs/2025-08-12/glo12-sla-4th-unet-noise2-19-24-46/glo12-sla-4th-unet/checkpoints/best.ckpt
#  config: ../outputs/2025-08-12/glo12-sla-4th-unet-noise2-19-24-46/.hydra/config.yaml

#  name: unet-noise2-gloss+-4th-glo12-sla-last2
#  checkpoint: ../outputs/2025-08-12/glo12-sla-4th-unet-noise2-gloss+-22-09-12/glo12-sla-4th-unet/checkpoints/last.ckpt
#  config: ../outputs/2025-08-12/glo12-sla-4th-unet-noise2-gloss+-22-09-12/.hydra/config.yaml

#  name: unet-noise2-8th-glo12-sla-best
#  checkpoint: ../outputs/2025-08-13/glo12-sla-8th-unet-14-57-16/glo12-sla-8th-unet/checkpoints/best.ckpt
#  config: ../outputs/2025-08-13/glo12-sla-8th-unet-14-57-16/.hydra/config.yaml

#  name: unet-noise2-8th-glo12-sla-2-best
#  checkpoint: ../outputs/2025-08-13/glo12-sla-8th-unet-11-57-45/glo12-sla-8th-unet/checkpoints/best.ckpt
#  config: ../outputs/2025-08-13/glo12-sla-8th-unet-11-57-45/.hydra/config.yaml

#  name: unet-wlonlat-noise+-8th-glo12-sla-last
#  checkpoint: ../outputs/2025-08-13/glo12-sla-8th-unet-wlonlat-noise+-20-11-34/glo12-sla-8th-unet-wlonlat/checkpoints/last.ckpt
#  config: ../outputs/2025-08-13/glo12-sla-8th-unet-wlonlat-noise+-20-11-34/.hydra/config.yaml
  
#  name: unet-wlonlat-noise-8th-glo12-sla-best
#  checkpoint: ../outputs/2025-08-14/glo12-sla-8th-unet-wlonlat-noise-15-06-40/glo12-sla-8th-unet-wlonlat/checkpoints/best.ckpt
#  config: ../outputs/2025-08-14/glo12-sla-8th-unet-wlonlat-noise-15-06-40/.hydra/config.yaml

#  name: fdv-latent-noise-8th-glo12-sla-last
#  checkpoint: ../outputs/2025-08-14/glo12-sla-8th-fdv-latent-08-16-14/glo12-sla-8th-4dvarnet-latent/checkpoints/last.ckpt
#  config: ../outputs/2025-08-14/glo12-sla-8th-fdv-latent-08-16-14//.hydra/config.yaml


# -----------------------------------------------------
# OSEE-OSE training, 1/4° config

  #name: unet-osse-osse-4th-best
  #checkpoint: ../outputs/2025-08-19/glo12-sla-4th-unet-ose-osse-07-48-14/glo12-sla-4th-unet-oseWosse/checkpoints/best.ckpt
  #config: ../outputs/2025-08-19/glo12-sla-4th-unet-ose-osse-07-48-14/.hydra/config.yaml

  #name: unet-osse-osse-4th-small-batches-2016-2018-best
  #checkpoint: ../outputs/2025-08-19/glo12-sla-4th-unet-ose-osse-small-batches-2016-2018-10-28-04/glo12-sla-4th-unet-oseWosse/checkpoints/best.ckpt
  #config: ../outputs/2025-08-19/glo12-sla-4th-unet-ose-osse-small-batches-2016-2018-10-28-04/.hydra/config.yaml


  #name: unet-osse-osse-4th-small-batches-inp-prepro-best
  #checkpoint: ../outputs/2025-08-19/glo12-sla-4th-unet-ose-osse-small-epochs-inp-prepro-19-09-34/glo12-sla-4th-unet-oseWosse/checkpoints/best.ckpt
  #config: ../outputs/2025-08-19/glo12-sla-4th-unet-ose-osse-small-epochs-inp-prepro-19-09-34/.hydra/config.yaml

  #name: unet-run2-4th-best
  #checkpoint: ../outputs/2025-08-20/glo12-sla-4th-unet-2010-2017-19-33-40/glo12-sla-4th-unet/checkpoints/best.ckpt
  #config: ../outputs/2025-08-20/glo12-sla-4th-unet-2010-2017-19-33-40/.hydra/config.yaml

  #name: unet-run2-osse-ose-4th-best
  #checkpoint: ../outputs/2025-08-20/glo12-sla-4th-unet-prepro-2010-2017-osse-ose-18-29-49/glo12-sla-4th-unet-oseWosse/checkpoints/best.ckpt
  #config: ../outputs/2025-08-20/glo12-sla-4th-unet-prepro-2010-2017-osse-ose-18-29-49/.hydra/config.yaml

  #name: unet-run2-osse-only-4th-best
  #checkpoint: ../outputs/2025-08-20/glo12-sla-4th-unet-osse-only-2010-2017-22-11-36/glo12-sla-4th-unet-oseWosse/checkpoints/best.ckpt
  #config: ../outputs/2025-08-20/glo12-sla-4th-unet-osse-only-2010-2017-22-11-36/.hydra/config.yaml

  #name: unet-osse-osse-4th-noise2-best
  #checkpoint: ../outputs/2025-08-21/glo12-sla-4th-unet-ose-osse-noise2-small-batches-2010-2017-23-33-18/glo12-sla-4th-unet-oseWosse/checkpoints/best.ckpt
  #config: ../outputs/2025-08-21/glo12-sla-4th-unet-ose-osse-noise2-small-batches-2010-2017-23-33-18/.hydra/config.yaml

  #name: unet-osse-osse-4th-noise2--best
  #checkpoint: ../outputs/2025-08-22/glo12-sla-4th-unet-ose-osse-noise2--small-batches-2010-2017-08-15-29/glo12-sla-4th-unet-oseWosse/checkpoints/best.ckpt
  #config: ../outputs/2025-08-22/glo12-sla-4th-unet-ose-osse-noise2--small-batches-2010-2017-08-15-29/.hydra/config.yaml

  #name: unet-run2-8th-best
  #checkpoint: ../outputs/2025-08-22/glo12-sla-8th-unet-18-18-28/glo12-sla-8th-unet/checkpoints/best.ckpt
  #config: ../outputs/2025-08-22/glo12-sla-8th-unet-18-18-28/.hydra/config.yaml

  #name: unet-1000epochs-run2-4th-best-nointerp
  #checkpoint: ../outputs/2025-08-22/glo12-sla-4th-unet-2010-2017-1000epochs-08-21-41/glo12-sla-4th-unet/checkpoints/best.ckpt
  #config: ../outputs/2025-08-22/glo12-sla-4th-unet-2010-2017-1000epochs-08-21-41/.hydra/config.yaml

  #name: unet-interp-relu-4th-best
  #checkpoint: ../outputs/2025-08-25/glo12-sla-4th-unet-interp-relu-17-00-19/glo12-sla-4th-unet/checkpoints/best.ckpt
  #config: ../outputs/2025-08-25/glo12-sla-4th-unet-interp-relu-17-00-19/.hydra/config.yaml
  
  #name: unet-interp-relu-4th-v2-best-nointerp
  #checkpoint: ../outputs/2025-08-27/glo12-sla-4th-unet-interp-relu-stride-22-38-10/glo12-sla-4th-unet/checkpoints/best.ckpt
  #config: ../outputs/2025-08-27/glo12-sla-4th-unet-interp-relu-stride-22-38-10/.hydra/config.yaml

  #name: unet-interp-silu-4th-v2-best
  #checkpoint: ../outputs/2025-08-25/glo12-sla-4th-unet-interp-silu-17-03-02/glo12-sla-4th-unet/checkpoints/best.ckpt
  #config: ../outputs/2025-08-25/glo12-sla-4th-unet-interp-silu-17-03-02/.hydra/config.yaml

  #name: fdv++-4th-best-stride-nointerp
  #checkpoint: ../outputs/2025-08-26/glo12-sla-4th-fdv++-13-23-14/glo12-sla-4th-fdv/checkpoints/best.ckpt
  #config: ../outputs/2025-08-26/glo12-sla-4th-fdv++-13-23-14/.hydra/config.yaml
  #checkpoint: ../outputs/2025-08-27/glo12-sla-4th-fdv++-stride-22-33-21/glo12-sla-4th-fdv/checkpoints/best.ckpt
  #config: ../outputs/2025-08-27/glo12-sla-4th-fdv++-stride-22-33-21/.hydra/config.yaml

  #name: fdv-latent++-4th-best-nointerp
  #checkpoint: ../outputs/2025-08-25/glo12-sla-4th-fdv-latent++-22-42-31/glo12-sla-4th-4dvarnet-latent/checkpoints/best.ckpt
  #config: ../outputs/2025-08-25/glo12-sla-4th-fdv-latent++-22-42-31/.hydra/config.yaml

  #name: fdv-latent+-4th-best
  #checkpoint: ../outputs/2025-08-25/glo12-sla-4th-fdv-latent+-22-30-32/glo12-sla-4th-4dvarnet-latent/checkpoints/best.ckpt
  #config: ../outputs/2025-08-25/glo12-sla-4th-fdv-latent+-22-30-32/.hydra/config.yaml

  #name: unet-si-only-4th-10iter-best
  #checkpoint: ../outputs/2025-08-25/glo12-sla-4th-unet-si-only-noise-2010-2017-1000epochs-20-25-15/glo12-sla-4th-unet-si/checkpoints/best.ckpt
  #config: ../outputs/2025-08-25/glo12-sla-4th-unet-si-only-noise-2010-2017-1000epochs-20-25-15/.hydra/config.yaml

  #name: fdv-latent++-4th-best-nointerp
  #checkpoint: ../outputs/2025-08-29/glo12-sla-4th-fdv-latent++-phi-1scale-16-29-56/glo12-sla-4th-fdv++latent/checkpoints/best.ckpt
  #config: ../outputs/2025-08-29/glo12-sla-4th-fdv-latent++-phi-1scale-16-29-56/.hydra/config.yaml

  #name: unet-noise++-4th-best-nointerp
  #checkpoint: ../outputs/2025-08-30/glo12-sla-4th-unet-noise++-10-48-46/glo12-sla-4th-unet/checkpoints/best.ckpt
  #config: ../outputs/2025-08-30/glo12-sla-4th-unet-noise++-10-48-46/.hydra/config.yaml

  #name: unet-noise+-4th-best-nointerp
  #checkpoint: ../outputs/2025-08-30/glo12-sla-4th-unet-noise+-10-42-21/glo12-sla-4th-unet/checkpoints/best.ckpt
  #config: ../outputs/2025-08-30/glo12-sla-4th-unet-noise+-10-42-21/.hydra/config.yaml

  #name: fdv++-4th-noise+-best-nointerp
  #checkpoint: ../outputs/2025-08-30/glo12-sla-4th-fdv++-noise+-10-13-47/glo12-sla-4th-fdv/checkpoints/best.ckpt
  #config: ../outputs/2025-08-30/glo12-sla-4th-fdv++-noise+-10-13-47/.hydra/config.yaml

  #name: fdv-latent++-4th-noise+-best-nointerp
  #checkpoint: ../outputs/2025-08-31/glo12-sla-4th-fdv-latent++-noise+-12-18-42/glo12-sla-4th-fdv++latent/checkpoints/best.ckpt
  #config: ../outputs/2025-08-31/glo12-sla-4th-fdv-latent++-noise+-12-18-42/.hydra/config.yaml

  #name: fdv-latent++-4th-noise++-best-nointerp
  #checkpoint: ../outputs/2025-08-31/glo12-sla-4th-fdv-latent++-noise+-12-19-26/glo12-sla-4th-fdv++latent/checkpoints/best.ckpt
  #config: ../outputs/2025-08-31/glo12-sla-4th-fdv-latent++-noise+-12-19-26/.hydra/config.yaml

  #name: fdv-4th-best-nointerp
  #checkpoint: ../outputs/2025-09-01/glo12-sla-4th-fdv-21-45-57/glo12-sla-4th-fdv/checkpoints/best.ckpt
  #onfig: ../outputs/2025-09-01/glo12-sla-4th-fdv-21-45-57/.hydra/config.yaml

  #name: fdv-4th-noise+-best-nointerp
  #checkpoint: ../outputs/2025-09-01/glo12-sla-4th-fdv-noise+-21-49-54/glo12-sla-4th-fdv/checkpoints/best.ckpt
  #config: ../outputs/2025-09-01/glo12-sla-4th-fdv-noise+-21-49-54/.hydra/config.yaml

  #name: twofdv-4th-best
  #checkpoint: ../outputs/2025-09-02/glo12-sla-4th-twofdv-20-47-00/glo12-sla-4th-twofdv/checkpoints/best.ckpt
  #config: ../outputs/2025-09-02/glo12-sla-4th-twofdv-20-47-00/.hydra/config.yaml

  #name: unet+-4th-noise++-best-nointerp
  #checkpoint: ../outputs/2025-09-03/glo12-sla-4th-unet-noise++-23-40-53/glo12-sla-4th-unet/checkpoints/best.ckpt
  #config: ../outputs/2025-09-03/glo12-sla-4th-unet-noise++-23-40-53/.hydra/config.yaml

  #name: fdv++-nonoise-best-nointerp
  #checkpoint: ../outputs/2025-09-03/glo12-sla-4th-fdv++-nonoise-21-50-18/glo12-sla-4th-fdv++/checkpoints/best.ckpt
  #config: ../outputs/2025-09-03/glo12-sla-4th-fdv++-nonoise-21-50-18/.hydra/config.yaml

  #name: unet-ose-only-1kepochs-best-nointerp
  #checkpoint: ../outputs/2025-09-06/glo12-sla-4th-unet-ose-only-2010-2017_1kepochs-16-02-10/glo12-sla-4th-unet-oseWosse/checkpoints/best.ckpt
  #config: ../outputs/2025-09-06/glo12-sla-4th-unet-ose-only-2010-2017_1kepochs-16-02-10/.hydra/config.yaml
  #checkpoint: ../outputs/2025-09-05/glo12-sla-4th-unet-ose-only-2010-2017-17-25-33/glo12-sla-4th-unet-oseWosse/checkpoints/best.ckpt
  #config: ../outputs/2025-09-05/glo12-sla-4th-unet-ose-only-2010-2017-17-25-33/.hydra/config.yaml

  #name: unet-ose-only-v2-best-nointerp
  #checkpoint: ../outputs/2025-09-06/glo12-sla-4th-unet-ose-only-v2-2010-2017_1kepochs-11-56-53/glo12-sla-4th-unet-oseWosse/checkpoints/best.ckpt
  #config: ../outputs/2025-09-06/glo12-sla-4th-unet-ose-only-v2-2010-2017_1kepochs-11-56-53/.hydra/config.yaml

  #name: unet-ose-withpostpro-best-nointerp
  #checkpoint: ../outputs/2025-09-07/glo12-sla-4th-unet-ose-withpostpro-2010-2017-19-37-01/glo12-sla-4th-unet-oseWosse/checkpoints/best.ckpt
  #config: ../outputs/2025-09-07/glo12-sla-4th-unet-ose-withpostpro-2010-2017-19-37-01/.hydra/config.yaml

  #name: unet-ose-withprepro-best-nointerp
  #checkpoint: ../outputs/2025-09-07/glo12-sla-4th-unet-ose-withprepro-2010-2017-17-37-00/glo12-sla-4th-unet-oseWosse/checkpoints/best.ckpt
  #config: ../outputs/2025-09-07/glo12-sla-4th-unet-ose-withprepro-2010-2017-17-37-00/.hydra/config.yaml

  #name: unet-ose-osse-4th-best-nointerp
  #checkpoint: ../outputs/2025-09-07/glo12-sla-4th-unet-ose-osse-2010-2017-12-55-44/glo12-sla-4th-unet-oseWosse/checkpoints/best.ckpt
  #config: ../outputs/2025-09-07/glo12-sla-4th-unet-ose-osse-2010-2017-12-55-44/.hydra/config.yaml  

  #name: unet-ose-only-withpostpro-4th-best-nointerp
  #checkpoint: ../outputs/2025-09-08/glo12-sla-4th-unet-ose-only-withpostpro-23-35-00/glo12-sla-4th-unet-oseWosse/checkpoints/best.ckpt
  #config: ../outputs/2025-09-08/glo12-sla-4th-unet-ose-only-withpostpro-23-35-00/.hydra/config.yaml

  #name: unet+-ose-osse-withpostpro-4th-best-nointerp
  #checkpoint: ../outputs/2025-09-08/glo12-sla-4th-unet+-ose-osse-withpostpro-20-52-48/glo12-sla-4th-unet+-oseWosse/checkpoints/best.ckpt
  #config: ../outputs/2025-09-08/glo12-sla-4th-unet+-ose-osse-withpostpro-20-52-48/.hydra/config.yaml

  #name: unet-nonoise-valossenoise-4th-nointerp
  #checkpoint: ../outputs/2025-09-09/glo12-sla-4th-unet-nonoise-16-24-43/glo12-sla-4th-unet/checkpoints/best.ckpt
  #config: ../outputs/2025-09-09/glo12-sla-4th-unet-nonoise-16-24-43/.hydra/config.yaml

  #name: unet-osse-only-2010-2017-from-scratch-4th-nointerp
  #checkpoint: ../outputs/2025-09-09/glo12-sla-4th-unet-osse-only-2010-2017-from-scratch-21-57-09/glo12-sla-4th-unet-oseWosse/checkpoints/best.ckpt
  #config: ../outputs/2025-09-09/glo12-sla-4th-unet-osse-only-2010-2017-from-scratch-21-57-09/.hydra/config.yaml
  
  #name: unet-ose-osse-4th-unet-ose-from-scratch
  #checkpoint: ../outputs/2025-09-09/glo12-sla-4th-unet-ose-osse-from-scratch-16-41-38/glo12-sla-4th-unet-oseWosse/checkpoints/best.ckpt
  #config: ../outputs/2025-09-09/glo12-sla-4th-unet-ose-osse-from-scratch-16-41-38/.hydra/config.yaml

  #name: unet-ose-osse-4th-unet-ose-osse-nopostpro
  #checkpoint: ../outputs/2025-09-09/glo12-sla-4th-unet-ose-osse-nopostpro-2010-2017-from-scratch-22-19-02/glo12-sla-4th-unet-oseWosse/checkpoints/best.ckpt
  #config: ../outputs/2025-09-09/glo12-sla-4th-unet-ose-osse-nopostpro-2010-2017-from-scratch-22-19-02/.hydra/config.yaml

  #name: unet-valmseWnoise-4th
  #checkpoint: ../outputs/2025-09-10/glo12-sla-4th-unet-valmseWnoise-18-24-52/glo12-sla-4th-unet/checkpoints/best.ckpt
  #config: ../outputs/2025-09-10/glo12-sla-4th-unet-valmseWnoise-18-24-52/.hydra/config.yaml

  #name: unet+-valmseWnoise-4th
  #checkpoint: ../outputs/2025-09-10/glo12-sla-4th-unet+-valmseWnoise-18-35-22/glo12-sla-4th-unet/checkpoints/best.ckpt
  #config: ../outputs/2025-09-10/glo12-sla-4th-unet+-valmseWnoise-18-35-22/.hydra/config.yaml

  #name: unet-noiseSpR-4th 
  #checkpoint: ../outputs/2025-09-10/glo12-sla-4th-unet+-noiseSpR-23-20-48/glo12-sla-4th-unet/checkpoints/best.ckpt
  #config: ../outputs/2025-09-10/glo12-sla-4th-unet+-noiseSpR-23-20-48/.hydra/config.yaml

  #name: unet+-noiseSpR-4th
  #checkpoint: ../outputs/2025-09-10/glo12-sla-4th-unet+-noiseSpR-23-20-07/glo12-sla-4th-unet/checkpoints/best.ckpt
  #config: ../outputs/2025-09-10/glo12-sla-4th-unet+-noiseSpR-23-20-07/.hydra/config.yaml

  #name: unet+-ose-osse-nopostpro-4th
  #checkpoint: ../outputs/2025-09-10/glo12-sla-4th-unet+-ose-osse-nopostpro-18-29-56/glo12-sla-4th-unet+-oseWosse/checkpoints/best.ckpt
  #config: ../outputs/2025-09-10/glo12-sla-4th-unet+-ose-osse-nopostpro-18-29-56/.hydra/config.yaml

  #name: unet-noiseSpRv2-4th
  #checkpoint: ../outputs/2025-09-11/glo12-sla-4th-unet-noiseSpRv2-15-43-19/glo12-sla-4th-unet/checkpoints/best.ckpt
  #config: ../outputs/2025-09-11/glo12-sla-4th-unet-noiseSpRv2-15-43-19/.hydra/config.yaml

  #name: unet+-noiseSpRv2-4th
  #checkpoint: ../outputs/2025-09-11/glo12-sla-4th-unet+-noiseSpRv2-21-26-55/glo12-sla-4th-unet/checkpoints/best.ckpt
  #config: ../outputs/2025-09-11/glo12-sla-4th-unet+-noiseSpRv2-21-26-55/.hydra/config.yaml

  #name: unet+-ose-osseSpRv2-nopostpro-4th
  #checkpoint: ../outputs/2025-09-11/glo12-sla-4th-unet+-ose-osseSpRv2-nopostpro-21-26-05/glo12-sla-4th-unet+-oseWosse/checkpoints/best.ckpt
  #config: ../outputs/2025-09-11/glo12-sla-4th-unet+-ose-osseSpRv2-nopostpro-21-26-05/.hydra/config.yaml

  #name: fdvunet-4th
  #checkpoint: ../outputs/2025-09-12/glo12-sla-4th-fdvunet-17-13-07/glo12-sla-4th-fdvunet/checkpoints/best.ckpt
  #config: ../outputs/2025-09-12/glo12-sla-4th-fdvunet-17-13-07/.hydra/config.yaml

  #name: unet+-noiseSpRv3-4th
  #checkpoint: ../outputs/2025-09-14/glo12-sla-4th-unet+-noiseSpRv3-21-36-25/glo12-sla-4th-unet/checkpoints/best.ckpt
  #config: ../outputs/2025-09-14/glo12-sla-4th-unet+-noiseSpRv3-21-36-25/.hydra/config.yaml

  name: unet+-noiseSpRv2-4th
  checkpoint: ../outputs/2025-09-14/glo12-sla-4th-unet+-noiseSpRv2-run2-12-29-41/glo12-sla-4th-unet/checkpoints/best.ckpt
  config: ../outputs/2025-09-14/glo12-sla-4th-unet+-noiseSpRv2-run2-12-29-41/.hydra/config.yaml