method:
  # -------------------------------------------------------------------
  # SLA
  # -------------------------------------------------------------------
  geo_uv: false
  normalization_type: none #norm_stats_from_patch
  obs_filtering: false #true
#  name: unet-4th-glo12-sla
#  checkpoint: ../outputs/2025-08-12/glo12-sla-4th-unet-12-52-27/glo12-sla-4th-unet/checkpoints/best.ckpt
#  config: ../outputs/2025-08-12/glo12-sla-4th-unet-12-52-27/.hydra/config.yaml

#  name: unet-4th-glo12-sla-with-init
#  checkpoint: ../outputs/2025-08-12/glo12-sla-4th-unet-with-init-12-52-56/glo12-sla-4th-unet-with-init/checkpoints/best.ckpt
#  config: ../outputs/2025-08-12/glo12-sla-4th-unet-with-init-12-52-56/.hydra/config.yaml

#  name: unet-noise2-4th-glo12-sla-best2
#  checkpoint: ../outputs/2025-08-12/glo12-sla-4th-unet-noise2-19-24-46/glo12-sla-4th-unet/checkpoints/best.ckpt
#  config: ../outputs/2025-08-12/glo12-sla-4th-unet-noise2-19-24-46/.hydra/config.yaml

#  name: unet-noise2-gloss+-4th-glo12-sla-last2
#  checkpoint: ../outputs/2025-08-12/glo12-sla-4th-unet-noise2-gloss+-22-09-12/glo12-sla-4th-unet/checkpoints/last.ckpt
#  config: ../outputs/2025-08-12/glo12-sla-4th-unet-noise2-gloss+-22-09-12/.hydra/config.yaml

#  name: unet-noise2-8th-glo12-sla-best
#  checkpoint: ../outputs/2025-08-13/glo12-sla-8th-unet-14-57-16/glo12-sla-8th-unet/checkpoints/best.ckpt
#  config: ../outputs/2025-08-13/glo12-sla-8th-unet-14-57-16/.hydra/config.yaml

#  name: unet-noise2-8th-glo12-sla-2-best
#  checkpoint: ../outputs/2025-08-13/glo12-sla-8th-unet-11-57-45/glo12-sla-8th-unet/checkpoints/best.ckpt
#  config: ../outputs/2025-08-13/glo12-sla-8th-unet-11-57-45/.hydra/config.yaml

#  name: unet-wlonlat-noise+-8th-glo12-sla-last
#  checkpoint: ../outputs/2025-08-13/glo12-sla-8th-unet-wlonlat-noise+-20-11-34/glo12-sla-8th-unet-wlonlat/checkpoints/last.ckpt
#  config: ../outputs/2025-08-13/glo12-sla-8th-unet-wlonlat-noise+-20-11-34/.hydra/config.yaml
  
#  name: unet-wlonlat-noise-8th-glo12-sla-best
#  checkpoint: ../outputs/2025-08-14/glo12-sla-8th-unet-wlonlat-noise-15-06-40/glo12-sla-8th-unet-wlonlat/checkpoints/best.ckpt
#  config: ../outputs/2025-08-14/glo12-sla-8th-unet-wlonlat-noise-15-06-40/.hydra/config.yaml

#  name: fdv-latent-noise-8th-glo12-sla-last
#  checkpoint: ../outputs/2025-08-14/glo12-sla-8th-fdv-latent-08-16-14/glo12-sla-8th-4dvarnet-latent/checkpoints/last.ckpt
#  config: ../outputs/2025-08-14/glo12-sla-8th-fdv-latent-08-16-14//.hydra/config.yaml


# -----------------------------------------------------
# OSEE-OSE training, 1/4° config
#  name: unet-osse-only-noise-4th-last
#  checkpoint: ../outputs/2025-08-18/glo12-sla-4th-unet-testosewosse-osse-only-12-33-24/glo12-sla-4th-unet-test/checkpoints/last.ckpt
#  config: ../outputs/2025-08-18/glo12-sla-4th-unet-testosewosse-osse-only-12-33-24/.hydra/config.yaml

#  name: unet-ose-osse-noise-4th-last
#  checkpoint: ../outputs/2025-08-18/glo12-sla-4th-unet-testosewosse-ose-osse-14-01-34/glo12-sla-4th-unet-test/checkpoints/last.ckpt
#  config: ../outputs/2025-08-18/glo12-sla-4th-unet-testosewosse-ose-osse-14-01-34/.hydra/config.yaml

  #name: unet-ose-only-noise-4th-last
  #checkpoint: ../outputs/2025-08-18/glo12-sla-4th-unet-testosewosse-ose-only-12-23-16/glo12-sla-4th-unet-test/checkpoints/last.ckpt
  #config: ../outputs/2025-08-18/glo12-sla-4th-unet-testosewosse-ose-only-12-23-16/.hydra/config.yaml
  #checkpoint: ../outputs/2025-08-18/glo12-sla-4th-unet-testosewosse-ose-only-14-12-51/glo12-sla-4th-unet-test/checkpoints/last.ckpt
  #config: ../outputs/2025-08-18/glo12-sla-4th-unet-testosewosse-ose-only-14-12-51/.hydra/config.yaml

  #name: unet-ose-osse-4th-last
  #checkpoint: ../outputs/2025-08-18/glo12-sla-4th-unet-testosewosse-ose-only-12-23-16/glo12-sla-4th-unet-test/checkpoints/last.ckpt
  #config: ../outputs/2025-08-18/glo12-sla-4th-unet-testosewosse-ose-only-12-23-16/.hydra/config.yaml
  #checkpoint: ../outputs/2025-08-18/glo12-sla-4th-unet-ose-osse-21-20-31/glo12-sla-4th-unet-oseWosse/checkpoints/last.ckpt
  #config: ../outputs/2025-08-18/glo12-sla-4th-unet-ose-osse-21-20-31/.hydra/config.yaml

  #name: unet-ose-only-4th-last
  #checkpoint: ../outputs/2025-08-18/glo12-sla-4th-unet-ose-only-21-15-38/glo12-sla-4th-unet-oseWosse/checkpoints/last.ckpt
  #config: ../outputs/2025-08-18/glo12-sla-4th-unet-ose-only-21-15-38/.hydra/config.yaml

  #name: unet-osse-only-4th-last
  #checkpoint: ../outputs/2025-08-18/glo12-sla-4th-unet-osse-only-21-23-55/glo12-sla-4th-unet-oseWosse/checkpoints/last.ckpt
  #config: ../outputs/2025-08-18/glo12-sla-4th-unet-osse-only-21-23-55/.hydra/config.yaml

  #name: unet-osse-osse-4th-small-batches-best
  #checkpoint: ../outputs/2025-08-19/glo12-sla-4th-unet-ose-osse-small-batches-07-44-31/glo12-sla-4th-unet-oseWosse/checkpoints/best.ckpt
  #config: ../outputs/2025-08-19/glo12-sla-4th-unet-ose-osse-small-batches-07-44-31/.hydra/config.yaml

  #name: unet-osse-osse-4th-best
  #checkpoint: ../outputs/2025-08-19/glo12-sla-4th-unet-ose-osse-07-48-14/glo12-sla-4th-unet-oseWosse/checkpoints/best.ckpt
  #config: ../outputs/2025-08-19/glo12-sla-4th-unet-ose-osse-07-48-14/.hydra/config.yaml

  #name: unet-osse-osse-4th-small-batches-2016-2018-best
  #checkpoint: ../outputs/2025-08-19/glo12-sla-4th-unet-ose-osse-small-batches-2016-2018-10-28-04/glo12-sla-4th-unet-oseWosse/checkpoints/best.ckpt
  #config: ../outputs/2025-08-19/glo12-sla-4th-unet-ose-osse-small-batches-2016-2018-10-28-04/.hydra/config.yaml


  #name: unet-osse-osse-4th-small-batches-inp-prepro-best
  #checkpoint: ../outputs/2025-08-19/glo12-sla-4th-unet-ose-osse-small-epochs-inp-prepro-19-09-34/glo12-sla-4th-unet-oseWosse/checkpoints/best.ckpt
  #config: ../outputs/2025-08-19/glo12-sla-4th-unet-ose-osse-small-epochs-inp-prepro-19-09-34/.hydra/config.yaml

  #name: unet-run2-4th-best
  #checkpoint: ../outputs/2025-08-20/glo12-sla-4th-unet-2010-2017-19-33-40/glo12-sla-4th-unet/checkpoints/best.ckpt
  #config: ../outputs/2025-08-20/glo12-sla-4th-unet-2010-2017-19-33-40/.hydra/config.yaml

  #name: unet-run2-osse-ose-4th-best
  #checkpoint: ../outputs/2025-08-20/glo12-sla-4th-unet-prepro-2010-2017-osse-ose-18-29-49/glo12-sla-4th-unet-oseWosse/checkpoints/best.ckpt
  #config: ../outputs/2025-08-20/glo12-sla-4th-unet-prepro-2010-2017-osse-ose-18-29-49/.hydra/config.yaml

  #name: unet-run2-osse-only-4th-best
  #checkpoint: ../outputs/2025-08-20/glo12-sla-4th-unet-osse-only-2010-2017-22-11-36/glo12-sla-4th-unet-oseWosse/checkpoints/best.ckpt
  #config: ../outputs/2025-08-20/glo12-sla-4th-unet-osse-only-2010-2017-22-11-36/.hydra/config.yaml

  #name: unet-osse-osse-4th-noise2-best
  #checkpoint: ../outputs/2025-08-21/glo12-sla-4th-unet-ose-osse-noise2-small-batches-2010-2017-23-33-18/glo12-sla-4th-unet-oseWosse/checkpoints/best.ckpt
  #config: ../outputs/2025-08-21/glo12-sla-4th-unet-ose-osse-noise2-small-batches-2010-2017-23-33-18/.hydra/config.yaml

  #name: unet-osse-osse-4th-noise2--best
  #checkpoint: ../outputs/2025-08-22/glo12-sla-4th-unet-ose-osse-noise2--small-batches-2010-2017-08-15-29/glo12-sla-4th-unet-oseWosse/checkpoints/best.ckpt
  #config: ../outputs/2025-08-22/glo12-sla-4th-unet-ose-osse-noise2--small-batches-2010-2017-08-15-29/.hydra/config.yaml

  #name: unet-run2-8th-best
  #checkpoint: ../outputs/2025-08-22/glo12-sla-8th-unet-18-18-28/glo12-sla-8th-unet/checkpoints/best.ckpt
  #config: ../outputs/2025-08-22/glo12-sla-8th-unet-18-18-28/.hydra/config.yaml

  #name: unet-1000epochs-run2-4th-best
  #checkpoint: ../outputs/2025-08-22/glo12-sla-4th-unet-2010-2017-1000epochs-08-21-41/glo12-sla-4th-unet/checkpoints/best.ckpt
  #config: ../outputs/2025-08-22/glo12-sla-4th-unet-2010-2017-1000epochs-08-21-41/.hydra/config.yaml

  #name: unet+-run2-8th-best-v1
  #checkpoint: ../outputs/2025-08-24/glo12-sla-8th-unet+-15-14-29/glo12-sla-8th-unet/checkpoints/best.ckpt
  #config: ../outputs/2025-08-24/glo12-sla-8th-unet+-15-14-29/.hydra/config.yaml

  name: unet-interp-relu-4th-best
  checkpoint: ../outputs/2025-08-25/glo12-sla-4th-unet-interp-relu-17-00-19/glo12-sla-4th-unet/checkpoints/best.ckpt
  config: ../outputs/2025-08-25/glo12-sla-4th-unet-interp-relu-17-00-19/.hydra/config.yaml

  #name: unet-interp-silu-4th-best
  #checkpoint: ../outputs/2025-08-25/glo12-sla-4th-unet-interp-silu-17-03-02/glo12-sla-4th-unet/checkpoints/best.ckpt
  #config: ../outputs/2025-08-25/glo12-sla-4th-unet-interp-silu-17-03-02/.hydra/config.yaml
